### ISSUE TITLE
Errors in Tweakscale patch?

### ISSUE THREAD

**Issue by lux7328** [Monniasza/Hyper-Drive-Mod#1]
https://github.com/net-lisias-ksp/TweakScale/discussions/291#discussion-4836164

This is the conversation that I had with the maintainer of tweakscale, He said that my issue is coming from the hyper drive mod patch for tweakscale. So, like I told him I don't know if this is an issue or if it is fine to keep using.

Please Help. @Monniasza 
<img width="515" alt="Screenshot 2023-02-08 000719" src="https://user-images.githubusercontent.com/124810519/217617335-db617c86-d849-40a0-a91c-ca83bd748d7e.png">

**Comment by Monniasza** [comment]
@lux7328 Did you use any other mods?

**Comment by Monniasza** [comment]
@ExodusSolis What is the `#@` at beginning of `#@TWEAKSCALEBEHAVIOR[fuelTank]/MODULE[TweakScale]{}`

**Comment by lux7328** [comment]
Yes I am using several other mods. And I dont know anything about coding, I don't even know where to find the code.

**Comment by Monniasza** [comment]
@lux7328 Try playing with only dependencies

**Comment by lux7328** [comment]
I don't know what that means.

**Comment by Monniasza** [comment]
I'll try changing it to '@' and test it with mods.

**Comment by lux7328** [comment]
I've been doing a lot of research.

<img width="395" alt="Screenshot Tqweakscale patch copy 7" src="https://user-images.githubusercontent.com/124810519/218148410-832eacf6-9606-4897-923c-0f1f15a4288c.png">

<img width="371" alt="Screenshot Tweakscale patch Copy 4" src="https://user-images.githubusercontent.com/124810519/218148428-0bfec84e-4761-4484-82a2-d546ff9965b3.png">

**Comment by Monniasza** [comment]
Fixed. 2.6 will be available soon. I've replaced erroneous `#@TWEAKSCALEBEHAVIOR` elements with `@TWEAKSCALEBEHAVIOR` at https://github.com/Monniasza/Hyper-Drive-Mod/commit/df3d787aa86ecf5f1569c326042af134b5d0d279

**Comment by Monniasza** [comment]
Use the KSP plugin for Visual Studio code at https://marketplace.visualstudio.com/items?itemName=al2me6.ksp-cfg-support
